#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re
import sys
import os
import argparse
from typing import Dict, Tuple, List, Set

HEADER_TEMPLATE = """// Auto-generated by proto_msg_mapper.py
// DO NOT EDIT MANUALLY

#pragma once

#include <cstdint>
#include <unordered_map>
#include <string>

// clang-format off
"""

FOOTER_TEMPLATE = """
// clang-format on
"""

def parse_proto_file(file_path: str) -> Dict[str, Tuple[int, str]]:
    """解析proto文件，返回消息类型到msg_id的映射"""
    pattern = re.compile(
        r'//\s*(?P<msg_id>\w+)\s*=\s*(?P<id>\d+).*?'
        r'message\s+(?P<msg_name>\w+)',
        re.DOTALL
    )
    
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    matches = pattern.finditer(content)
    return {
        match.group('msg_name'): (int(match.group('id')), match.group('msg_id'))
        for match in matches
    }

def find_proto_files(input_paths: List[str], exclude_patterns: List[str]) -> List[str]:
    """查找所有proto文件，排除指定模式"""
    proto_files = set()
    
    for path in input_paths:
        if os.path.isfile(path):
            if path.endswith('.proto') and not any(p in path for p in exclude_patterns):
                proto_files.add(os.path.abspath(path))
        elif os.path.isdir(path):
            for root, _, files in os.walk(path):
                for file in files:
                    if file.endswith('.proto'):
                        full_path = os.path.join(root, file)
                        if not any(p in full_path for p in exclude_patterns):
                            proto_files.add(full_path)
    
    return sorted(proto_files)

def generate_cpp_header(mappings: List[Dict[str, Tuple[int, str]]], output_path: str):
    """生成C++头文件"""
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(HEADER_TEMPLATE)
        
        # 合并所有映射并检查冲突
        merged_mapping = {}
        id_conflicts = set()
        name_conflicts = set()
        
        for mapping in mappings:
            for name, (msg_id, msg_id_str) in mapping.items():
                if msg_id in merged_mapping and merged_mapping[msg_id][0] != name:
                    id_conflicts.add(msg_id)
                if name in merged_mapping and merged_mapping[name][0] != msg_id:
                    name_conflicts.add(name)
                merged_mapping[name] = (msg_id, msg_id_str)
        
        if id_conflicts:
            print(f"Warning: Found {len(id_conflicts)} ID conflicts: {sorted(id_conflicts)}")
        if name_conflicts:
            print(f"Warning: Found {len(name_conflicts)} name conflicts: {sorted(name_conflicts)}")
        
        # 生成消息类型到ID的映射
        f.write("// Message name to ID mapping\n")
        f.write("static const std::unordered_map<std::string, uint32_t> kMsgNameToId = {\n")
        for msg_name, (msg_id, _) in sorted(merged_mapping.items(), key=lambda x: x[1][0]):
            f.write(f'    {{"{msg_name}", {msg_id}}},\n')
        f.write("};\n\n")
        
        # 生成ID到消息类型的映射
        f.write("// ID to message name mapping\n")
        f.write("static const std::unordered_map<uint32_t, std::string> kIdToMsgName = {\n")
        for msg_name, (msg_id, _) in sorted(merged_mapping.items(), key=lambda x: x[1][0]):
            f.write(f'    {{{msg_id}, "{msg_name}"}},\n')
        f.write("};\n\n")
        
        # 生成ID到msg_id字符串的映射
        f.write("// ID to msg_id string mapping\n")
        f.write("static const std::unordered_map<uint32_t, std::string> kIdToMsgIdStr = {\n")
        for _, (msg_id, msg_id_str) in sorted(merged_mapping.items(), key=lambda x: x[1][0]):
            f.write(f'    {{{msg_id}, "{msg_id_str}"}},\n')
        f.write("};\n\n")
        
        # 生成msg_id字符串到ID的映射
        f.write("// msg_id string to ID mapping\n")
        f.write("static const std::unordered_map<std::string, uint32_t> kMsgIdStrToId = {\n")
        for _, (msg_id, msg_id_str) in sorted(merged_mapping.items(), key=lambda x: x[1][0]):
            f.write(f'    {{"{msg_id_str}", {msg_id}}},\n')
        f.write("};\n")
        
        f.write(FOOTER_TEMPLATE)

def main():
    parser = argparse.ArgumentParser(
        description='Generate C++ message mapping from proto files',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument('output', help='Output header file path')
    parser.add_argument('inputs', nargs='+', help='Input proto files or directories')
    parser.add_argument('--exclude', nargs='*', default=[], 
                       help='Exclude files containing these patterns')
    args = parser.parse_args()
    
    # 查找所有proto文件
    proto_files = find_proto_files(args.inputs, args.exclude)
    if not proto_files:
        print("Error: No proto files found in input paths")
        sys.exit(1)
    
    # print(f"Found {len(proto_files)} proto files:")
    # for f in proto_files:
    #     print(f"  {f}")
    
    # 解析所有proto文件
    mappings = []
    for proto_file in proto_files:
        try:
            mappings.append(parse_proto_file(proto_file))
        except Exception as e:
            print(f"Error parsing {proto_file}: {str(e)}")
            sys.exit(1)
    
    # 生成头文件
    generate_cpp_header(mappings, args.output)
    total_messages = sum(len(m) for m in mappings)
    print(f"Successfully generated {args.output} with {total_messages} message mappings")

if __name__ == "__main__":
    main()
