// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

#include "core.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace ss {
PROTOBUF_CONSTEXPR HeartBeat::HeartBeat(
    ::_pbi::ConstantInitialized) {}
struct HeartBeatDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HeartBeatDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HeartBeatDefaultTypeInternal() {}
  union {
    HeartBeat _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HeartBeatDefaultTypeInternal _HeartBeat_default_instance_;
PROTOBUF_CONSTEXPR RegistToCenter_Request::RegistToCenter_Request(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.local_info_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RegistToCenter_RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RegistToCenter_RequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RegistToCenter_RequestDefaultTypeInternal() {}
  union {
    RegistToCenter_Request _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RegistToCenter_RequestDefaultTypeInternal _RegistToCenter_Request_default_instance_;
PROTOBUF_CONSTEXPR RegistToCenter_Response::RegistToCenter_Response(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.err_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RegistToCenter_ResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RegistToCenter_ResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RegistToCenter_ResponseDefaultTypeInternal() {}
  union {
    RegistToCenter_Response _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RegistToCenter_ResponseDefaultTypeInternal _RegistToCenter_Response_default_instance_;
PROTOBUF_CONSTEXPR RegistToCenter::RegistToCenter(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.request_)*/nullptr
  , /*decltype(_impl_.response_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RegistToCenterDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RegistToCenterDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RegistToCenterDefaultTypeInternal() {}
  union {
    RegistToCenter _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RegistToCenterDefaultTypeInternal _RegistToCenter_default_instance_;
PROTOBUF_CONSTEXPR CenterServiceMap_Request::CenterServiceMap_Request(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.local_info_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CenterServiceMap_RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CenterServiceMap_RequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CenterServiceMap_RequestDefaultTypeInternal() {}
  union {
    CenterServiceMap_Request _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CenterServiceMap_RequestDefaultTypeInternal _CenterServiceMap_Request_default_instance_;
PROTOBUF_CONSTEXPR CenterServiceMap_Response::CenterServiceMap_Response(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.service_info_map_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CenterServiceMap_ResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CenterServiceMap_ResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CenterServiceMap_ResponseDefaultTypeInternal() {}
  union {
    CenterServiceMap_Response _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CenterServiceMap_ResponseDefaultTypeInternal _CenterServiceMap_Response_default_instance_;
PROTOBUF_CONSTEXPR CenterServiceMap::CenterServiceMap(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.request_)*/nullptr
  , /*decltype(_impl_.response_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CenterServiceMapDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CenterServiceMapDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CenterServiceMapDefaultTypeInternal() {}
  union {
    CenterServiceMap _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CenterServiceMapDefaultTypeInternal _CenterServiceMap_default_instance_;
}  // namespace ss
static ::_pb::Metadata file_level_metadata_core_2eproto[7];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_core_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_core_2eproto = nullptr;

const uint32_t TableStruct_core_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ss::HeartBeat, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ss::RegistToCenter_Request, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ss::RegistToCenter_Request, _impl_.local_info_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ss::RegistToCenter_Response, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ss::RegistToCenter_Response, _impl_.err_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ss::RegistToCenter, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ss::RegistToCenter, _impl_.request_),
  PROTOBUF_FIELD_OFFSET(::ss::RegistToCenter, _impl_.response_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ss::CenterServiceMap_Request, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ss::CenterServiceMap_Request, _impl_.local_info_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ss::CenterServiceMap_Response, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ss::CenterServiceMap_Response, _impl_.service_info_map_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ss::CenterServiceMap, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ss::CenterServiceMap, _impl_.request_),
  PROTOBUF_FIELD_OFFSET(::ss::CenterServiceMap, _impl_.response_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ss::HeartBeat)},
  { 6, -1, -1, sizeof(::ss::RegistToCenter_Request)},
  { 13, -1, -1, sizeof(::ss::RegistToCenter_Response)},
  { 20, -1, -1, sizeof(::ss::RegistToCenter)},
  { 28, -1, -1, sizeof(::ss::CenterServiceMap_Request)},
  { 35, -1, -1, sizeof(::ss::CenterServiceMap_Response)},
  { 42, -1, -1, sizeof(::ss::CenterServiceMap)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::ss::_HeartBeat_default_instance_._instance,
  &::ss::_RegistToCenter_Request_default_instance_._instance,
  &::ss::_RegistToCenter_Response_default_instance_._instance,
  &::ss::_RegistToCenter_default_instance_._instance,
  &::ss::_CenterServiceMap_Request_default_instance_._instance,
  &::ss::_CenterServiceMap_Response_default_instance_._instance,
  &::ss::_CenterServiceMap_default_instance_._instance,
};

const char descriptor_table_protodef_core_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\ncore.proto\022\002ss\032\rss_base.proto\032\021ss_err_"
  "code.proto\"\013\n\tHeartBeat\"\303\001\n\016RegistToCent"
  "er\022+\n\007request\030\001 \001(\0132\032.ss.RegistToCenter."
  "Request\022-\n\010response\030\002 \001(\0132\033.ss.RegistToC"
  "enter.Response\032.\n\007Request\022#\n\nlocal_info\030"
  "\001 \001(\0132\017.ss.ServiceInfo\032%\n\010Response\022\031\n\003er"
  "r\030\001 \001(\0162\014.SSErrorCode\"\331\001\n\020CenterServiceM"
  "ap\022-\n\007request\030\001 \001(\0132\034.ss.CenterServiceMa"
  "p.Request\022/\n\010response\030\002 \001(\0132\035.ss.CenterS"
  "erviceMap.Response\032.\n\007Request\022#\n\nlocal_i"
  "nfo\030\001 \001(\0132\017.ss.ServiceInfo\0325\n\010Response\022)"
  "\n\020service_info_map\030\001 \003(\0132\017.ss.ServiceInf"
  "ob\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_core_2eproto_deps[2] = {
  &::descriptor_table_ss_5fbase_2eproto,
  &::descriptor_table_ss_5ferr_5fcode_2eproto,
};
static ::_pbi::once_flag descriptor_table_core_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_core_2eproto = {
    false, false, 489, descriptor_table_protodef_core_2eproto,
    "core.proto",
    &descriptor_table_core_2eproto_once, descriptor_table_core_2eproto_deps, 2, 7,
    schemas, file_default_instances, TableStruct_core_2eproto::offsets,
    file_level_metadata_core_2eproto, file_level_enum_descriptors_core_2eproto,
    file_level_service_descriptors_core_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_core_2eproto_getter() {
  return &descriptor_table_core_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_core_2eproto(&descriptor_table_core_2eproto);
namespace ss {

// ===================================================================

class HeartBeat::_Internal {
 public:
};

HeartBeat::HeartBeat(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:ss.HeartBeat)
}
HeartBeat::HeartBeat(const HeartBeat& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  HeartBeat* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ss.HeartBeat)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HeartBeat::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HeartBeat::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata HeartBeat::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_core_2eproto_getter, &descriptor_table_core_2eproto_once,
      file_level_metadata_core_2eproto[0]);
}

// ===================================================================

class RegistToCenter_Request::_Internal {
 public:
  static const ::ss::ServiceInfo& local_info(const RegistToCenter_Request* msg);
};

const ::ss::ServiceInfo&
RegistToCenter_Request::_Internal::local_info(const RegistToCenter_Request* msg) {
  return *msg->_impl_.local_info_;
}
void RegistToCenter_Request::clear_local_info() {
  if (GetArenaForAllocation() == nullptr && _impl_.local_info_ != nullptr) {
    delete _impl_.local_info_;
  }
  _impl_.local_info_ = nullptr;
}
RegistToCenter_Request::RegistToCenter_Request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ss.RegistToCenter.Request)
}
RegistToCenter_Request::RegistToCenter_Request(const RegistToCenter_Request& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RegistToCenter_Request* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.local_info_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_local_info()) {
    _this->_impl_.local_info_ = new ::ss::ServiceInfo(*from._impl_.local_info_);
  }
  // @@protoc_insertion_point(copy_constructor:ss.RegistToCenter.Request)
}

inline void RegistToCenter_Request::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.local_info_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

RegistToCenter_Request::~RegistToCenter_Request() {
  // @@protoc_insertion_point(destructor:ss.RegistToCenter.Request)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RegistToCenter_Request::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.local_info_;
}

void RegistToCenter_Request::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RegistToCenter_Request::Clear() {
// @@protoc_insertion_point(message_clear_start:ss.RegistToCenter.Request)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.local_info_ != nullptr) {
    delete _impl_.local_info_;
  }
  _impl_.local_info_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RegistToCenter_Request::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .ss.ServiceInfo local_info = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_local_info(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RegistToCenter_Request::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ss.RegistToCenter.Request)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .ss.ServiceInfo local_info = 1;
  if (this->_internal_has_local_info()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::local_info(this),
        _Internal::local_info(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ss.RegistToCenter.Request)
  return target;
}

size_t RegistToCenter_Request::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ss.RegistToCenter.Request)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .ss.ServiceInfo local_info = 1;
  if (this->_internal_has_local_info()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.local_info_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RegistToCenter_Request::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RegistToCenter_Request::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RegistToCenter_Request::GetClassData() const { return &_class_data_; }


void RegistToCenter_Request::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RegistToCenter_Request*>(&to_msg);
  auto& from = static_cast<const RegistToCenter_Request&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ss.RegistToCenter.Request)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_local_info()) {
    _this->_internal_mutable_local_info()->::ss::ServiceInfo::MergeFrom(
        from._internal_local_info());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RegistToCenter_Request::CopyFrom(const RegistToCenter_Request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ss.RegistToCenter.Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RegistToCenter_Request::IsInitialized() const {
  return true;
}

void RegistToCenter_Request::InternalSwap(RegistToCenter_Request* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.local_info_, other->_impl_.local_info_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RegistToCenter_Request::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_core_2eproto_getter, &descriptor_table_core_2eproto_once,
      file_level_metadata_core_2eproto[1]);
}

// ===================================================================

class RegistToCenter_Response::_Internal {
 public:
};

RegistToCenter_Response::RegistToCenter_Response(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ss.RegistToCenter.Response)
}
RegistToCenter_Response::RegistToCenter_Response(const RegistToCenter_Response& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RegistToCenter_Response* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.err_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.err_ = from._impl_.err_;
  // @@protoc_insertion_point(copy_constructor:ss.RegistToCenter.Response)
}

inline void RegistToCenter_Response::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.err_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

RegistToCenter_Response::~RegistToCenter_Response() {
  // @@protoc_insertion_point(destructor:ss.RegistToCenter.Response)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RegistToCenter_Response::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void RegistToCenter_Response::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RegistToCenter_Response::Clear() {
// @@protoc_insertion_point(message_clear_start:ss.RegistToCenter.Response)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.err_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RegistToCenter_Response::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .SSErrorCode err = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_err(static_cast<::SSErrorCode>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RegistToCenter_Response::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ss.RegistToCenter.Response)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .SSErrorCode err = 1;
  if (this->_internal_err() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_err(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ss.RegistToCenter.Response)
  return target;
}

size_t RegistToCenter_Response::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ss.RegistToCenter.Response)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .SSErrorCode err = 1;
  if (this->_internal_err() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_err());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RegistToCenter_Response::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RegistToCenter_Response::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RegistToCenter_Response::GetClassData() const { return &_class_data_; }


void RegistToCenter_Response::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RegistToCenter_Response*>(&to_msg);
  auto& from = static_cast<const RegistToCenter_Response&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ss.RegistToCenter.Response)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_err() != 0) {
    _this->_internal_set_err(from._internal_err());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RegistToCenter_Response::CopyFrom(const RegistToCenter_Response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ss.RegistToCenter.Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RegistToCenter_Response::IsInitialized() const {
  return true;
}

void RegistToCenter_Response::InternalSwap(RegistToCenter_Response* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.err_, other->_impl_.err_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RegistToCenter_Response::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_core_2eproto_getter, &descriptor_table_core_2eproto_once,
      file_level_metadata_core_2eproto[2]);
}

// ===================================================================

class RegistToCenter::_Internal {
 public:
  static const ::ss::RegistToCenter_Request& request(const RegistToCenter* msg);
  static const ::ss::RegistToCenter_Response& response(const RegistToCenter* msg);
};

const ::ss::RegistToCenter_Request&
RegistToCenter::_Internal::request(const RegistToCenter* msg) {
  return *msg->_impl_.request_;
}
const ::ss::RegistToCenter_Response&
RegistToCenter::_Internal::response(const RegistToCenter* msg) {
  return *msg->_impl_.response_;
}
RegistToCenter::RegistToCenter(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ss.RegistToCenter)
}
RegistToCenter::RegistToCenter(const RegistToCenter& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RegistToCenter* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.request_){nullptr}
    , decltype(_impl_.response_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_request()) {
    _this->_impl_.request_ = new ::ss::RegistToCenter_Request(*from._impl_.request_);
  }
  if (from._internal_has_response()) {
    _this->_impl_.response_ = new ::ss::RegistToCenter_Response(*from._impl_.response_);
  }
  // @@protoc_insertion_point(copy_constructor:ss.RegistToCenter)
}

inline void RegistToCenter::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.request_){nullptr}
    , decltype(_impl_.response_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

RegistToCenter::~RegistToCenter() {
  // @@protoc_insertion_point(destructor:ss.RegistToCenter)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RegistToCenter::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.request_;
  if (this != internal_default_instance()) delete _impl_.response_;
}

void RegistToCenter::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RegistToCenter::Clear() {
// @@protoc_insertion_point(message_clear_start:ss.RegistToCenter)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.request_ != nullptr) {
    delete _impl_.request_;
  }
  _impl_.request_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.response_ != nullptr) {
    delete _impl_.response_;
  }
  _impl_.response_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RegistToCenter::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .ss.RegistToCenter.Request request = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_request(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .ss.RegistToCenter.Response response = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_response(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RegistToCenter::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ss.RegistToCenter)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .ss.RegistToCenter.Request request = 1;
  if (this->_internal_has_request()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::request(this),
        _Internal::request(this).GetCachedSize(), target, stream);
  }

  // .ss.RegistToCenter.Response response = 2;
  if (this->_internal_has_response()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::response(this),
        _Internal::response(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ss.RegistToCenter)
  return target;
}

size_t RegistToCenter::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ss.RegistToCenter)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .ss.RegistToCenter.Request request = 1;
  if (this->_internal_has_request()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.request_);
  }

  // .ss.RegistToCenter.Response response = 2;
  if (this->_internal_has_response()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.response_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RegistToCenter::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RegistToCenter::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RegistToCenter::GetClassData() const { return &_class_data_; }


void RegistToCenter::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RegistToCenter*>(&to_msg);
  auto& from = static_cast<const RegistToCenter&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ss.RegistToCenter)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_request()) {
    _this->_internal_mutable_request()->::ss::RegistToCenter_Request::MergeFrom(
        from._internal_request());
  }
  if (from._internal_has_response()) {
    _this->_internal_mutable_response()->::ss::RegistToCenter_Response::MergeFrom(
        from._internal_response());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RegistToCenter::CopyFrom(const RegistToCenter& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ss.RegistToCenter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RegistToCenter::IsInitialized() const {
  return true;
}

void RegistToCenter::InternalSwap(RegistToCenter* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RegistToCenter, _impl_.response_)
      + sizeof(RegistToCenter::_impl_.response_)
      - PROTOBUF_FIELD_OFFSET(RegistToCenter, _impl_.request_)>(
          reinterpret_cast<char*>(&_impl_.request_),
          reinterpret_cast<char*>(&other->_impl_.request_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RegistToCenter::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_core_2eproto_getter, &descriptor_table_core_2eproto_once,
      file_level_metadata_core_2eproto[3]);
}

// ===================================================================

class CenterServiceMap_Request::_Internal {
 public:
  static const ::ss::ServiceInfo& local_info(const CenterServiceMap_Request* msg);
};

const ::ss::ServiceInfo&
CenterServiceMap_Request::_Internal::local_info(const CenterServiceMap_Request* msg) {
  return *msg->_impl_.local_info_;
}
void CenterServiceMap_Request::clear_local_info() {
  if (GetArenaForAllocation() == nullptr && _impl_.local_info_ != nullptr) {
    delete _impl_.local_info_;
  }
  _impl_.local_info_ = nullptr;
}
CenterServiceMap_Request::CenterServiceMap_Request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ss.CenterServiceMap.Request)
}
CenterServiceMap_Request::CenterServiceMap_Request(const CenterServiceMap_Request& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CenterServiceMap_Request* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.local_info_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_local_info()) {
    _this->_impl_.local_info_ = new ::ss::ServiceInfo(*from._impl_.local_info_);
  }
  // @@protoc_insertion_point(copy_constructor:ss.CenterServiceMap.Request)
}

inline void CenterServiceMap_Request::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.local_info_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CenterServiceMap_Request::~CenterServiceMap_Request() {
  // @@protoc_insertion_point(destructor:ss.CenterServiceMap.Request)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CenterServiceMap_Request::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.local_info_;
}

void CenterServiceMap_Request::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CenterServiceMap_Request::Clear() {
// @@protoc_insertion_point(message_clear_start:ss.CenterServiceMap.Request)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.local_info_ != nullptr) {
    delete _impl_.local_info_;
  }
  _impl_.local_info_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CenterServiceMap_Request::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .ss.ServiceInfo local_info = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_local_info(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CenterServiceMap_Request::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ss.CenterServiceMap.Request)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .ss.ServiceInfo local_info = 1;
  if (this->_internal_has_local_info()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::local_info(this),
        _Internal::local_info(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ss.CenterServiceMap.Request)
  return target;
}

size_t CenterServiceMap_Request::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ss.CenterServiceMap.Request)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .ss.ServiceInfo local_info = 1;
  if (this->_internal_has_local_info()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.local_info_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CenterServiceMap_Request::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CenterServiceMap_Request::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CenterServiceMap_Request::GetClassData() const { return &_class_data_; }


void CenterServiceMap_Request::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CenterServiceMap_Request*>(&to_msg);
  auto& from = static_cast<const CenterServiceMap_Request&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ss.CenterServiceMap.Request)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_local_info()) {
    _this->_internal_mutable_local_info()->::ss::ServiceInfo::MergeFrom(
        from._internal_local_info());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CenterServiceMap_Request::CopyFrom(const CenterServiceMap_Request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ss.CenterServiceMap.Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CenterServiceMap_Request::IsInitialized() const {
  return true;
}

void CenterServiceMap_Request::InternalSwap(CenterServiceMap_Request* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.local_info_, other->_impl_.local_info_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CenterServiceMap_Request::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_core_2eproto_getter, &descriptor_table_core_2eproto_once,
      file_level_metadata_core_2eproto[4]);
}

// ===================================================================

class CenterServiceMap_Response::_Internal {
 public:
};

void CenterServiceMap_Response::clear_service_info_map() {
  _impl_.service_info_map_.Clear();
}
CenterServiceMap_Response::CenterServiceMap_Response(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ss.CenterServiceMap.Response)
}
CenterServiceMap_Response::CenterServiceMap_Response(const CenterServiceMap_Response& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CenterServiceMap_Response* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.service_info_map_){from._impl_.service_info_map_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ss.CenterServiceMap.Response)
}

inline void CenterServiceMap_Response::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.service_info_map_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CenterServiceMap_Response::~CenterServiceMap_Response() {
  // @@protoc_insertion_point(destructor:ss.CenterServiceMap.Response)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CenterServiceMap_Response::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.service_info_map_.~RepeatedPtrField();
}

void CenterServiceMap_Response::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CenterServiceMap_Response::Clear() {
// @@protoc_insertion_point(message_clear_start:ss.CenterServiceMap.Response)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.service_info_map_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CenterServiceMap_Response::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .ss.ServiceInfo service_info_map = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_service_info_map(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CenterServiceMap_Response::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ss.CenterServiceMap.Response)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .ss.ServiceInfo service_info_map = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_service_info_map_size()); i < n; i++) {
    const auto& repfield = this->_internal_service_info_map(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ss.CenterServiceMap.Response)
  return target;
}

size_t CenterServiceMap_Response::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ss.CenterServiceMap.Response)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .ss.ServiceInfo service_info_map = 1;
  total_size += 1UL * this->_internal_service_info_map_size();
  for (const auto& msg : this->_impl_.service_info_map_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CenterServiceMap_Response::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CenterServiceMap_Response::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CenterServiceMap_Response::GetClassData() const { return &_class_data_; }


void CenterServiceMap_Response::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CenterServiceMap_Response*>(&to_msg);
  auto& from = static_cast<const CenterServiceMap_Response&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ss.CenterServiceMap.Response)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.service_info_map_.MergeFrom(from._impl_.service_info_map_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CenterServiceMap_Response::CopyFrom(const CenterServiceMap_Response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ss.CenterServiceMap.Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CenterServiceMap_Response::IsInitialized() const {
  return true;
}

void CenterServiceMap_Response::InternalSwap(CenterServiceMap_Response* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.service_info_map_.InternalSwap(&other->_impl_.service_info_map_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CenterServiceMap_Response::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_core_2eproto_getter, &descriptor_table_core_2eproto_once,
      file_level_metadata_core_2eproto[5]);
}

// ===================================================================

class CenterServiceMap::_Internal {
 public:
  static const ::ss::CenterServiceMap_Request& request(const CenterServiceMap* msg);
  static const ::ss::CenterServiceMap_Response& response(const CenterServiceMap* msg);
};

const ::ss::CenterServiceMap_Request&
CenterServiceMap::_Internal::request(const CenterServiceMap* msg) {
  return *msg->_impl_.request_;
}
const ::ss::CenterServiceMap_Response&
CenterServiceMap::_Internal::response(const CenterServiceMap* msg) {
  return *msg->_impl_.response_;
}
CenterServiceMap::CenterServiceMap(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ss.CenterServiceMap)
}
CenterServiceMap::CenterServiceMap(const CenterServiceMap& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CenterServiceMap* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.request_){nullptr}
    , decltype(_impl_.response_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_request()) {
    _this->_impl_.request_ = new ::ss::CenterServiceMap_Request(*from._impl_.request_);
  }
  if (from._internal_has_response()) {
    _this->_impl_.response_ = new ::ss::CenterServiceMap_Response(*from._impl_.response_);
  }
  // @@protoc_insertion_point(copy_constructor:ss.CenterServiceMap)
}

inline void CenterServiceMap::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.request_){nullptr}
    , decltype(_impl_.response_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CenterServiceMap::~CenterServiceMap() {
  // @@protoc_insertion_point(destructor:ss.CenterServiceMap)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CenterServiceMap::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.request_;
  if (this != internal_default_instance()) delete _impl_.response_;
}

void CenterServiceMap::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CenterServiceMap::Clear() {
// @@protoc_insertion_point(message_clear_start:ss.CenterServiceMap)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.request_ != nullptr) {
    delete _impl_.request_;
  }
  _impl_.request_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.response_ != nullptr) {
    delete _impl_.response_;
  }
  _impl_.response_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CenterServiceMap::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .ss.CenterServiceMap.Request request = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_request(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .ss.CenterServiceMap.Response response = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_response(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CenterServiceMap::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ss.CenterServiceMap)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .ss.CenterServiceMap.Request request = 1;
  if (this->_internal_has_request()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::request(this),
        _Internal::request(this).GetCachedSize(), target, stream);
  }

  // .ss.CenterServiceMap.Response response = 2;
  if (this->_internal_has_response()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::response(this),
        _Internal::response(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ss.CenterServiceMap)
  return target;
}

size_t CenterServiceMap::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ss.CenterServiceMap)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .ss.CenterServiceMap.Request request = 1;
  if (this->_internal_has_request()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.request_);
  }

  // .ss.CenterServiceMap.Response response = 2;
  if (this->_internal_has_response()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.response_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CenterServiceMap::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CenterServiceMap::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CenterServiceMap::GetClassData() const { return &_class_data_; }


void CenterServiceMap::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CenterServiceMap*>(&to_msg);
  auto& from = static_cast<const CenterServiceMap&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ss.CenterServiceMap)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_request()) {
    _this->_internal_mutable_request()->::ss::CenterServiceMap_Request::MergeFrom(
        from._internal_request());
  }
  if (from._internal_has_response()) {
    _this->_internal_mutable_response()->::ss::CenterServiceMap_Response::MergeFrom(
        from._internal_response());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CenterServiceMap::CopyFrom(const CenterServiceMap& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ss.CenterServiceMap)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CenterServiceMap::IsInitialized() const {
  return true;
}

void CenterServiceMap::InternalSwap(CenterServiceMap* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CenterServiceMap, _impl_.response_)
      + sizeof(CenterServiceMap::_impl_.response_)
      - PROTOBUF_FIELD_OFFSET(CenterServiceMap, _impl_.request_)>(
          reinterpret_cast<char*>(&_impl_.request_),
          reinterpret_cast<char*>(&other->_impl_.request_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CenterServiceMap::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_core_2eproto_getter, &descriptor_table_core_2eproto_once,
      file_level_metadata_core_2eproto[6]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ss
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ss::HeartBeat*
Arena::CreateMaybeMessage< ::ss::HeartBeat >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ss::HeartBeat >(arena);
}
template<> PROTOBUF_NOINLINE ::ss::RegistToCenter_Request*
Arena::CreateMaybeMessage< ::ss::RegistToCenter_Request >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ss::RegistToCenter_Request >(arena);
}
template<> PROTOBUF_NOINLINE ::ss::RegistToCenter_Response*
Arena::CreateMaybeMessage< ::ss::RegistToCenter_Response >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ss::RegistToCenter_Response >(arena);
}
template<> PROTOBUF_NOINLINE ::ss::RegistToCenter*
Arena::CreateMaybeMessage< ::ss::RegistToCenter >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ss::RegistToCenter >(arena);
}
template<> PROTOBUF_NOINLINE ::ss::CenterServiceMap_Request*
Arena::CreateMaybeMessage< ::ss::CenterServiceMap_Request >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ss::CenterServiceMap_Request >(arena);
}
template<> PROTOBUF_NOINLINE ::ss::CenterServiceMap_Response*
Arena::CreateMaybeMessage< ::ss::CenterServiceMap_Response >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ss::CenterServiceMap_Response >(arena);
}
template<> PROTOBUF_NOINLINE ::ss::CenterServiceMap*
Arena::CreateMaybeMessage< ::ss::CenterServiceMap >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ss::CenterServiceMap >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
