// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: err_code.proto

#include "err_code.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

static const ::_pb::EnumDescriptor* file_level_enum_descriptors_err_5fcode_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_err_5fcode_2eproto = nullptr;
const uint32_t TableStruct_err_5fcode_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_err_5fcode_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016err_code.proto*\235\002\n\tErrorCode\022\021\n\rError_"
  "unknown\020\000\022\021\n\rError_success\020\001\022\022\n\016Error_ar"
  "gument\020\003\022\020\n\013Error_muted\020\202\001\022\025\n\020Error_no_c"
  "hannel\020\203\001\022\027\n\022Error_msg_too_long\020\204\001\022\024\n\017Er"
  "ror_wrong_msg\020\205\001\022\021\n\014Error_no_msg\020\206\001\022\025\n\020E"
  "rror_block_self\020\207\001\022\025\n\020Error_chat_in_cd\020\210"
  "\001\022\"\n\035Error_block_player_over_limit\020\211\001\022\031\n"
  "\024Error_item_num_limit\020\212\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_err_5fcode_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_err_5fcode_2eproto = {
    false, false, 312, descriptor_table_protodef_err_5fcode_2eproto,
    "err_code.proto",
    &descriptor_table_err_5fcode_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_err_5fcode_2eproto::offsets,
    nullptr, file_level_enum_descriptors_err_5fcode_2eproto,
    file_level_service_descriptors_err_5fcode_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_err_5fcode_2eproto_getter() {
  return &descriptor_table_err_5fcode_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_err_5fcode_2eproto(&descriptor_table_err_5fcode_2eproto);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ErrorCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_err_5fcode_2eproto);
  return file_level_enum_descriptors_err_5fcode_2eproto[0];
}
bool ErrorCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 3:
    case 130:
    case 131:
    case 132:
    case 133:
    case 134:
    case 135:
    case 136:
    case 137:
    case 138:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
