// Auto-generated by proto_msg_mapper.py
// DO NOT EDIT MANUALLY

#pragma once

#include <cstdint>
#include <unordered_map>
#include <string>

// clang-format off
// Message name to ID mapping
static const std::unordered_map<std::string, uint32_t> kMsgNameToId = {
    {"PlayerSendMessage", 250},
    {"PlayerReqMessage", 251},
    {"Notify", 10000},
};

// ID to message name mapping
static const std::unordered_map<uint32_t, std::string> kIdToMsgName = {
    {250, "PlayerSendMessage"},
    {251, "PlayerReqMessage"},
    {10000, "Notify"},
};

// ID to msg_id string mapping
static const std::unordered_map<uint32_t, std::string> kIdToMsgIdStr = {
    {250, "CS_PLAYER_SEND_MESSAGE"},
    {251, "CS_PLAYER_REQ_MESSAGE"},
    {10000, "SC_NOTIFY"},
};

// msg_id string to ID mapping
static const std::unordered_map<std::string, uint32_t> kMsgIdStrToId = {
    {"CS_PLAYER_SEND_MESSAGE", 250},
    {"CS_PLAYER_REQ_MESSAGE", 251},
    {"SC_NOTIFY", 10000},
};

// clang-format on
