// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notify.proto

#include "notify.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace cs {
PROTOBUF_CONSTEXPR Notify::Notify(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.chat_message_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct NotifyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NotifyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~NotifyDefaultTypeInternal() {}
  union {
    Notify _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NotifyDefaultTypeInternal _Notify_default_instance_;
}  // namespace cs
static ::_pb::Metadata file_level_metadata_notify_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_notify_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_notify_2eproto = nullptr;

const uint32_t TableStruct_notify_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cs::Notify, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cs::Notify, _impl_.chat_message_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::cs::Notify)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::cs::_Notify_default_instance_._instance,
};

const char descriptor_table_protodef_notify_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014notify.proto\022\002cs\032\nbase.proto\"/\n\006Notify"
  "\022%\n\014chat_message\030\001 \001(\0132\017.cs.ChatMessageb"
  "\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_notify_2eproto_deps[1] = {
  &::descriptor_table_base_2eproto,
};
static ::_pbi::once_flag descriptor_table_notify_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_notify_2eproto = {
    false, false, 87, descriptor_table_protodef_notify_2eproto,
    "notify.proto",
    &descriptor_table_notify_2eproto_once, descriptor_table_notify_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_notify_2eproto::offsets,
    file_level_metadata_notify_2eproto, file_level_enum_descriptors_notify_2eproto,
    file_level_service_descriptors_notify_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_notify_2eproto_getter() {
  return &descriptor_table_notify_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_notify_2eproto(&descriptor_table_notify_2eproto);
namespace cs {

// ===================================================================

class Notify::_Internal {
 public:
  static const ::cs::ChatMessage& chat_message(const Notify* msg);
};

const ::cs::ChatMessage&
Notify::_Internal::chat_message(const Notify* msg) {
  return *msg->_impl_.chat_message_;
}
void Notify::clear_chat_message() {
  if (GetArenaForAllocation() == nullptr && _impl_.chat_message_ != nullptr) {
    delete _impl_.chat_message_;
  }
  _impl_.chat_message_ = nullptr;
}
Notify::Notify(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:cs.Notify)
}
Notify::Notify(const Notify& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Notify* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.chat_message_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_chat_message()) {
    _this->_impl_.chat_message_ = new ::cs::ChatMessage(*from._impl_.chat_message_);
  }
  // @@protoc_insertion_point(copy_constructor:cs.Notify)
}

inline void Notify::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.chat_message_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Notify::~Notify() {
  // @@protoc_insertion_point(destructor:cs.Notify)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Notify::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.chat_message_;
}

void Notify::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Notify::Clear() {
// @@protoc_insertion_point(message_clear_start:cs.Notify)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.chat_message_ != nullptr) {
    delete _impl_.chat_message_;
  }
  _impl_.chat_message_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Notify::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .cs.ChatMessage chat_message = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_chat_message(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Notify::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cs.Notify)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .cs.ChatMessage chat_message = 1;
  if (this->_internal_has_chat_message()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::chat_message(this),
        _Internal::chat_message(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cs.Notify)
  return target;
}

size_t Notify::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cs.Notify)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .cs.ChatMessage chat_message = 1;
  if (this->_internal_has_chat_message()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.chat_message_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Notify::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Notify::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Notify::GetClassData() const { return &_class_data_; }


void Notify::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Notify*>(&to_msg);
  auto& from = static_cast<const Notify&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cs.Notify)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_chat_message()) {
    _this->_internal_mutable_chat_message()->::cs::ChatMessage::MergeFrom(
        from._internal_chat_message());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Notify::CopyFrom(const Notify& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cs.Notify)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Notify::IsInitialized() const {
  return true;
}

void Notify::InternalSwap(Notify* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.chat_message_, other->_impl_.chat_message_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Notify::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_notify_2eproto_getter, &descriptor_table_notify_2eproto_once,
      file_level_metadata_notify_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace cs
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::cs::Notify*
Arena::CreateMaybeMessage< ::cs::Notify >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cs::Notify >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
